### ISSUE TITLE
Upload to PyPI if not yet

### ISSUE THREAD

**Issue by part1zano** [yakudzam/Flask-Disqus#1]
Hi, i'm about to create a FreeBSD port for this extension, and it would be genuinely nice if you told me whether or not you were going to upload this to PyPI.

**Comment by maksymx** [comment]
Hi @part1zano 
yes, I'll upload this extension to PyPI soon

**Comment by part1zano** [comment]
That would be great! Thank you in advance.

**Comment by maksymx** [comment]
@part1zano 
https://pypi.python.org/pypi?name=Flask-Disqus&version=0.0.1&:action=display

**Comment by part1zano** [comment]
@yakudzam Yay, thanks!
